### ISSUE TITLE
Table of contents of the jupyter book

### ISSUE THREAD

**Issue by niklassiemer** [materialdigital/PMD-workflow-workshop#3]
In these lines of the workflow the `_toc.yml` file for the jupyter book is generated on the fly. To control what enters in which order you should include an own `_toc.yml` file and omit this overwriting here. 
https://github.com/materialdigital/PMD-workflow-workshop/blob/32f0282e92eed9f99cb679c1f31788ba914d2d6f/.github/workflows/book.yml#L27-L28

**Comment by muh-hassani** [comment]
Great. Thank a lot, @niklassiemer. So I will replace the `_toc.yml` file as you mentioned.

**Comment by muh-hassani** [comment]
@niklassiemer, after a few iteration, I found out (in the link below) that the order of the notebooks, in the navigation sidebar, is alphabetical. Then I gave up and renamed my notebooks.
[https://jupyterbook.org/customize/toc.html#automatically-generate-your-toc-yml-file](https://jupyterbook.org/customize/toc.html#automatically-generate-your-toc-yml-file)

**Comment by niklassiemer** [comment]
@muh-hassani If you want control about the ordering, you have to write the toc yourself. E.g.
```
- file: README.md
- file: 1stNotebook.ipynb
- file: 2ndNotebook.ipynb
```
However, renaming notebooks to be in alphabetical order is also fine.
